import { test, expect } from "@playwright/test";
import { readFile } from "node:fs/promises";

async function reachCoursework(page, includeUCLA = true) {
  await page.goto("/");
  await expect(page.getByRole("navigation", { name: "Transfer planning progress" })).toHaveCount(0);
  const homeSchool = page.locator("label.school-tile", { hasText: "San Diego Miramar College" });
  if (page.viewportSize().width >= 1100) {
    const schoolBox = await homeSchool.boundingBox();
    expect(schoolBox.width).toBeGreaterThanOrEqual(190);
    expect(schoolBox.height).toBeGreaterThanOrEqual(158);
  }
  await homeSchool.click();
  await page.getByRole("button", { name: /Choose my destinations/ }).click();
  await page.locator("label.school-tile", { hasText: "UC Berkeley" }).click();
  if (includeUCLA) await page.locator("label.school-tile", { hasText: "UCLA" }).click();
  await page.getByRole("button", { name: /Choose my major/ }).click();
  await expect(page.getByText("Choose this major", { exact: true })).toHaveCount(0);
  const majorTile = page.locator(".major-tile", { hasText: "Computer Science" });
  await expect(page.locator(".major-tile")).toHaveCount(6);
  const majorTileBox = await majorTile.boundingBox();
  expect(majorTileBox.height).toBeGreaterThanOrEqual(136);
  expect(majorTileBox.width / majorTileBox.height).toBeLessThan(1.35);
  await majorTile.click();
  await expect(majorTile).toHaveAttribute("aria-pressed", "true");
  await expect(page.getByLabel("Intended major")).toHaveValue("Computer Science");
  await page.getByRole("button", { name: /Add my coursework/ }).click();
  await expect(page.locator("#onboarding-main>.eyebrow")).toHaveText("STEP 04 / 04");
  await expect(page.getByRole("navigation", { name: "ASSIST agreement workflow" })).toBeVisible();
}

test("single-destination recommendations use the visual score gauge", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name.includes("mobile"), "Covered by the focused mobile test");
  await reachCoursework(page, false);
  const math150 = page.locator('[data-course-tile="miramar_math150"]').first();
  await math150.getByRole("button", { name: /MATH 150/ }).click();
  await math150.getByRole("button", { name: "Completed" }).click();
  await page.locator(".agreement-journey button").last().click();
  await page.getByRole("button", { name: /See my transfer plan/ }).click();
  await expect(page.locator(".efficiency-dial")).toHaveAttribute("aria-label", /\d+ out of 100, Strong recommendation/);
  await expect(page.locator(".efficiency-dial strong")).toHaveText(/^\d{1,3}$/);
  await expect(page.locator(".efficiency-verdict strong")).toHaveText("STRONG");
  const math151Score = await page.evaluate(() => courseCandidates().find(item => item.c.code === "MATH 151").efficiencyScore);
  expect(math151Score).toBe(77);
});

test("Miramar to Berkeley and UCLA supports grouped decisions, completion and efficiency", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name.includes("mobile"), "Covered by the focused mobile test");
  await reachCoursework(page);
  await expect(page.locator(".agreement-journey")).toContainText("Group A");
  await expect(page.locator(".agreement-journey")).toContainText("Group B");
  const math150 = page.locator('[data-course-tile="miramar_math150"]').first();
  await math150.getByRole("button", { name: /MATH 150/ }).click();
  await math150.getByRole("button", { name: "Completed" }).click();
  await expect(math150).toHaveClass(/status-completed/);
  await page.locator(".agreement-journey button").last().click();
  await page.getByRole("button", { name: /See my transfer plan/ }).click();
  const transferPlanWidth = await page.locator("#main").evaluate(el => el.getBoundingClientRect().width);
  expect(transferPlanWidth).toBeLessThanOrEqual(1180);
  await expect(page.getByText("Transfer Efficiency", { exact: true })).toBeVisible();
  await expect(page.locator(".efficiency-dial strong")).toHaveText(/^\d{1,3}$/);
  await expect(page.locator(".efficiency-dial span")).toHaveText("/100");
  await expect(page.locator(".efficiency-verdict")).toContainText(/recommendation/i);
  await expect(page.locator(".efficiency-summary")).toContainText("transfer leverage");
  await page.getByRole("button", { name: /What this score means/ }).click();
  await expect(page.getByText("85–100")).toBeVisible();
  await expect(page.locator("#detail-dialog").getByText(/not an admission probability/i)).toBeVisible();
  await page.getByRole("button", { name: /Close/ }).click();
  await page.evaluate(() => setCourseStatus(nextMove().c.id, "planning"));
  await page.getByRole("button", { name: /View course details and availability/ }).click();
  await expect(page.getByRole("heading", { name: /Course details and availability/ })).toBeVisible();
  const courseAvailability = page.locator("#detail-dialog details.schedule");
  await expect(courseAvailability).toBeVisible();
  await courseAvailability.locator("summary").click();
  await expect(courseAvailability.locator(".schedule-head")).toBeVisible();
  await page.getByRole("button", { name: /Close/ }).click();
  await expect(page.getByText("Course relationships—not admission readiness", { exact: true })).toHaveCount(0);
  await expect(page.getByText("No complete eligibility or admissions assessment.", { exact: true })).toHaveCount(0);
  const offering = page.locator("details.schedule:has(.section-row)").first();
  await expect(offering).not.toHaveAttribute("open", "");
  await expect(offering.locator(".section-row").first()).toBeHidden();
  await offering.locator("summary").click();
  await expect(offering.locator(".section-row").first()).toBeVisible();
  await page.getByRole("button", { name: /Review & export/ }).click();
  await expect(page.getByRole("heading", { name: "Take your plan with you." })).toBeVisible();
  await expect(page.getByRole("navigation", { name: "Transfer planning progress" })).toHaveCount(0);
  await expect(page.getByText("Transfer Completion", { exact: true }).first()).toBeVisible();
  await expect(page.locator(".export-grid")).toContainText("PDF");
  await expect(page.locator(".export-grid")).toContainText("Word");
  await expect(page.locator(".export-grid")).toContainText("Excel");
  await expect(page.locator(".export-grid")).toContainText("Markdown");
  const [markdownDownload] = await Promise.all([page.waitForEvent("download"), page.getByRole("button", { name: /Markdown/ }).click()]);
  expect(await readFile(await markdownDownload.path(), "utf8")).toContain("## Transfer Completion");
  await markdownDownload.saveAs(testInfo.outputPath("transfer-plan.md"));
  const [wordDownload] = await Promise.all([page.waitForEvent("download"), page.getByRole("button", { name: /Word/ }).click()]);
  expect((await readFile(await wordDownload.path())).toString("latin1")).toContain("word/document.xml");
  await wordDownload.saveAs(testInfo.outputPath("transfer-plan.docx"));
  const [excelDownload] = await Promise.all([page.waitForEvent("download"), page.getByRole("button", { name: /Excel/ }).click()]);
  expect((await readFile(await excelDownload.path())).toString("latin1")).toContain("xl/workbook.xml");
  await excelDownload.saveAs(testInfo.outputPath("transfer-plan.xlsx"));
  const [pdfReport] = await Promise.all([page.waitForEvent("popup"), page.getByRole("button", { name: /^PDF/ }).click()]);
  await expect(pdfReport).toHaveTitle("Transfer Copilot plan");
  await expect(pdfReport.getByRole("heading", { name: "Transfer Copilot plan" })).toBeVisible();
  await pdfReport.close();
  await page.getByRole("button", { name: /Back to my transfer plan/ }).click();
  await expect(page.getByText("Transfer Efficiency", { exact: true })).toBeVisible();
  await expect(page.locator(".efficiency-dial strong")).toHaveText(/^\d{1,3}$/);
  await expect(page.locator(".efficiency-summary")).toContainText("selected destinations");
  const recommendationBefore = await page.locator(".next-course>strong").textContent() + ":" + await page.locator(".efficiency-dial strong").textContent();
  await page.evaluate(() => setCourseStatus(nextMove().c.id, "completed"));
  const recommendationAfter = await page.locator(".next-course>strong").textContent() + ":" + await page.locator(".efficiency-dial strong").textContent();
  expect(recommendationAfter).not.toBe(recommendationBefore);
  const mapping = page.locator(".fit-row", { hasText: "MATH 150" }).first();
  await expect(mapping.locator(".fit-dest")).toHaveCount(2);
  await expect(mapping).toContainText("UC Berkeley");
  await expect(mapping).toContainText("UCLA");
});

test("mobile coursework keeps the workflow usable without page overflow", async ({ page }, testInfo) => {
  test.skip(!testInfo.project.name.includes("mobile"), "Mobile-only layout assertion");
  await reachCoursework(page);
  const sizes = await page.evaluate(() => ({ scroll: document.documentElement.scrollWidth, client: document.documentElement.clientWidth }));
  expect(sizes.scroll).toBeLessThanOrEqual(sizes.client + 1);
  await expect(page.locator("#onboarding-main>.eyebrow")).toHaveText("STEP 04 / 04");
  const map = page.locator(".articulation-map").first();
  const columns = await map.evaluate(el => getComputedStyle(el).gridTemplateColumns.split(" ").length);
  expect(columns).toBe(1);
});
